### ISSUE TITLE
Property 'groupBy' does not exist on type 'ObjectConstructor'.

### ISSUE THREAD

**Issue by xcollantes** [xcollantes/portfolio#74]
In `portfolio/components/ExperienceCards.tsx`, error when deploying or running `npm run builid`.  

```
Type error: Property 'groupBy' does not exist on type 'ObjectConstructor'.

  46 |   useEffect(() => {
  47 |     
> 48 |     const split = Object.groupBy(selected, (e: MetadataType) => e.articleType)
     |                          ^
  49 |     setWorkExps(split.WORKEXP)
  50 |     setBlogs(split.BLOG)
  51 |     console.log(split)
```

```js
const split = Object.groupBy(selected, (e: MetadataType) => e.articleType)
```

**Comment by xcollantes** [comment]
https://github.com/microsoft/TypeScript/issues/47171

**Comment by xcollantes** [comment]
The code will ship in TypeScript 5.4.

**Comment by xcollantes** [comment]
Fatal error in Safari browsers: https://github.com/xcollantes/portfolio/issues/75

**Comment by benaventeadrian** [comment]
Hi! I'm have TypeScript 5.6 and the error still persists. I'd appreciate any updates on this. Thanks!

**Comment by benaventeadrian** [comment]
Hi! I have TypeScript 5.6 and the error is still present. I'd appreciate any updates on this. Thanks!

**Comment by JustMikey** [comment]
The solution seems to be adding `ESNext` to `tsconfig -> compilerOptions -> lib`

**Comment by clefayomide** [comment]
> The solution seems to be adding `ESNext` to `tsconfig -> compilerOptions -> lib`

your solution worked at compile time, thanks, but i got same error during build, upgrading to typescript v5.7.0 fixed the build error
